general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Lock the screen (10 minutes)
listener {
    timeout = 600                               # 10 minutes (600 seconds)
    on-timeout = loginctl lock-session          # Lock screen when timeout has passed
}

# Put the computer to sleep (1 hour)
listener {
    timeout = 3600                              # 1 hour (7200 seconds)
    on-timeout = systemctl suspend              # Suspend the PC
}