# ~/.config/hypr/hyprlock.conf

general {
  hide_cursor = true
  grace = 0
  ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

# auth {
#     fingerprint:enabled = true
#     fingerprint:ready_message = Scan your fingerprint to unlock
#     fingerprint:present_message = Scanning...
#     fingerprint:retry_delay = 250
# }

# INPUT FIELD
input-field {
  monitor = 
  size = 400, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(0, 0, 0, 1.0)  # Black
  inner_color = rgba(25, 25, 25, 1.0)  # Dark gray
  font_color = rgba(255, 255, 255, 1.0)  # White
  fade_on_empty = false
  placeholder_text = Logged in as $USER
  hide_input = false
  check_color = rgba(0, 255, 0, 1.0)  # Green
  fail_color = rgba(255, 0, 0, 1.0)  # Red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = rgba(255, 255, 0, 1.0)  # Yellow
  position = 0, -47
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = $TIME
  color = rgba(255, 255, 255, 1.0)  # White
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] LC_TIME=en_US.UTF-8 date +"%A, %d %B %Y"
  color = rgba(255, 255, 255, 1.0)  # White
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = rgba(255, 255, 255, 1.0)  # White
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}